kind: Kustomization
resources:
  - ../../manifests # directory that also has a kustomization.yaml to import
patches:
  - target: # resource we want to patch
      kind: Deployment
      name: wordpress
    path: wordpress-deployment-patches.yaml # patch file
  # add more resources

# TODO: finish this