kind: Kustomization
resources:
  - ../../manifests
patches:
  - target: # resource we want to patch
      kind: Deployment
      name: wordpress
    path: wordpress-deployment-patches.yaml # patch file
  # add more resources

# TODO: finish this