apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress-dev
  labels:
    app: wordpress
spec:
  ports:
    - port: 8080
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
