kind: Kustomization
resources: # directories (or single files) to pull manifests from
  - wordpress
  - mysql

secretGenerator:
  - name: mysql-pass
    namespace: wordpress-dev
    label: app=wordpress-dev
    literals:
      - password=t3stp@55