kind: Kustomization
resources: # directories (or single files) to pull manifests from
  - wordpress
  - mysql

secretGenerator:
  - name: mysql-pass
    options:
      disableNameSuffixHash: true
    literals:
      - password=t3stp@55